config/routes.rb
Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Avo::Engine, at: Avo.configuration.root_path
    Avo::Engine.routes.draw do
      # This route is not protected, secure it with authentication if needed.
      get "dashboard", to: "tools#dashboard", as: :dashboard
      post "login_as/:id", to: "tools#login_as", as: :login_as
    end
  end
  resources :accounts, only: [ :create ] do
    resources :account_users, only: %i[create index destroy], module: :accounts
    member do
      get :switch
    end
  end
  namespace :inbound_webhooks do
    resources :github, controller: :github, only: [ :create ]
    resources :gitlab, controller: :gitlab, only: [ :create ]
  end
  get "/privacy", to: "static#privacy"
  get "/terms", to: "static#terms"

  authenticated :user do
    root to: "projects#index", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end
  get "/integrations/github/repositories", to: "integrations/github/repositories#index"
  resources :add_ons do
    collection do
      get :search
      get :default_values
    end
    member do
      post :restart
    end
    resource :metrics, only: [ :show ], module: :add_ons
    resources :endpoints, only: %i[edit update], module: :add_ons
    resources :processes, only: %i[index show], module: :add_ons
  end

  resources :providers, only: %i[index new create destroy]
  resources :projects do
    member do
      post :restart
    end
    collection do
      get "/:project_id/deployments", to: "projects/deployments#index", as: :root
    end
    resources :project_forks, only: %i[index edit create], module: :projects
    resources :volumes, only: %i[index new create destroy], module: :projects
    resources :processes, only: %i[index show create destroy], module: :projects
    resources :services, only: %i[index new create destroy update], module: :projects do
      resources :jobs, only: %i[create], module: :services
      resources :domains, only: %i[create destroy], module: :services do
        collection do
          post :check_dns
        end
      end
    end
    resources :metrics, only: [ :index ], module: :projects
    resources :project_add_ons, only: %i[create destroy], module: :projects
    resources :environment_variables, only: %i[index create destroy], module: :projects
    resources :deployments, only: %i[index show], module: :projects do
      collection do
        post :deploy
      end
      member do
        post :redeploy
        patch :kill
      end
    end
  end
  resources :clusters do
    member do
      post :transfer_ownership
      get :download_kubeconfig
      get :download_yaml
      get :logs
    end
    resource :metrics, only: [ :show ], module: :clusters
    resource :build_cloud, only: [ :show, :edit, :update, :create, :destroy ], module: :clusters
    member do
      post :test_connection
      post :retry_install
    end
    collection do
      post :check_k3s_ip_address
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      mount Flipper::UI.app(Flipper) => '/flipper', as: :flipper
      mount GoodJob::Engine => "/good_job"
    end
  end

  resources :notifications, only: [ :index ]
  resources :announcements, only: [ :index ]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: "users/sessions" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "async_render" => "async_renderer#async_render"

  get "/calculator", to: "static#calculator"
  # Public marketing homepage
  if Rails.application.config.local_mode
    get "/github_token", to: "local/pages#github_token"
    put "/github_token", to: "local/pages#update_github_token"
    namespace :local do
      resources :onboarding, only: [ :index ]
      resource :portainer, only: [ :show, :update ] do
        collection do
          get :github_oauth
        end
      end
    end
    root to: "projects#index"
  else
    root to: "static#index"
  end
end

app/views/shared/_default_right_nav.html.erb
<li>
  <div>
    <%# <%= link_to t(".connected_accounts"), user_connected_accounts_path, class: 'text-gray-800 bg-white hover:bg-primary-50 dark:text-gray-50 dark:bg-gray-800 dark:hover:bg-primary-800 transition ease-in-out duration-200 whitespace-nowrap no-underline block px-6 py-3' if Devise.omniauth_configs.any? %>
    <%# <%= link_to t(".accounts"), accounts_path, class: 'text-gray-800 bg-white hover:bg-primary-50 dark:text-gray-50 dark:bg-gray-800 dark:hover:bg-primary-800 transition ease-in-out duration-200 whitespace-nowrap no-underline block px-6 py-3' %>
    <%#= link_to t(".api_tokens"), api_tokens_path, class: 'text-gray-800 bg-white hover:bg-primary-50 dark:text-gray-50 dark:bg-gray-800 dark:hover:bg-primary-800 transition ease-in-out duration-200 whitespace-nowrap no-underline block px-6 py-3' if Jumpstart.config.payments_enabled? %>
    <%= link_to edit_user_registration_path do %>
      <iconify-icon icon="lucide:user" height="16"></iconify-icon>
      Account
    <% end %>
  </div>
  <div>
    <%= link_to providers_path do %>
      <iconify-icon icon="lucide:key-round" height="16"></iconify-icon>
      Credentials
    <% end %>
  </div>
  <div>
    <%= link_to "https://docs.canine.sh/", target: "_blank" do %>
      <iconify-icon icon="lucide:book-open"></iconify-icon>
      <span>Documentation</span>
    <% end %>
  </div>
</li>
<% if current_user.admin? %>
  <li>
    <div>
      <%= link_to avo_path do %>
        <iconify-icon icon="lucide:lock-keyhole" height="16"></iconify-icon>
        Admin
      <% end %>
    </div>
  </li>
  <li>
    <div>
      <%= link_to admin_flipper_path do %>
        <iconify-icon icon="lucide:flag" height="16"></iconify-icon>
        Feature Flags
      <% end %>
    </div>
  </li>
  <li>
    <div>
      <%= link_to admin_good_job_path do %>
        <iconify-icon icon="lucide:server" height="16"></iconify-icon>
        Jobs
      <% end %>
    </div>
  </li>
<% end %>
<hr class="-mx-2 my-1 border-base-content/10">
<li>
  <div class="text-error">
    <%= link_to destroy_user_session_path, method: :delete do %>
      <iconify-icon icon="lucide:log-out" height="16"></iconify-icon>
      Logout
    <% end %>
  </div>
</li>

app/views/shared/_head.html.erb
<title>
  <% if content_for?(:title) %>
    <%= yield :title %> |
  <% end %>
  Canine - An open source alternative to Heroku
</title>
<meta name="description" content="Canine is an open source deployment platform that makes it easy to deploy and manage your applications.">

<% if content_for?(:og_title) %>
  <meta property="og:title" content="<%= yield :og_title %>" />
<% else %>
  <meta property="og:title" content="Canine - An open source alternative to Heroku" />
<% end %>

<% if content_for?(:og_url) %>
  <meta property="og:url" content="<%= yield :og_url %>" />
<% else %>
  <meta property="og:url" content="https://canine.sh" />
<% end %>

<% if content_for?(:og_description) %>
  <meta property="og:description" content="<%= yield :og_description %>" />
<% else %>
  <meta property="og:description" content="Canine is an open source deployment platform that makes it easy to deploy and manage your applications." />
<% end %>

<% if content_for?(:og_image) %>
  <meta property="og:image" content="<%= yield :og_image %>" />
<% else %>
  <meta property="og:image" content="https://canine.sh/images/deployment_styled.png" />
<% end %>
<meta http-equiv="content-language" content="<%= I18n.locale %>"/>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="theme-color" content="#191b1f">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
<%= render "shared/favicons" %>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preload" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
<script src="https://cdn.jsdelivr.net/npm/iconify-icon@2.1.0/dist/iconify-icon.min.js"></script>
<% if ENV["POSTHOG_KEY"].present? %>
  <script>
      !function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.crossOrigin="anonymous",p.async=!0,p.src=s.api_host.replace(".i.posthog.com","-assets.i.posthog.com")+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="init capture register register_once register_for_session unregister unregister_for_session getFeatureFlag getFeatureFlagPayload isFeatureEnabled reloadFeatureFlags updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures on onFeatureFlags onSessionId getSurveys getActiveMatchingSurveys renderSurvey canRenderSurvey getNextSurveyStep identify setPersonProperties group resetGroups setPersonPropertiesForFlags resetPersonPropertiesForFlags setGroupPropertiesForFlags resetGroupPropertiesForFlags reset get_distinct_id getGroups get_session_id get_session_replay_url alias set_config startSessionRecording stopSessionRecording sessionRecordingStarted captureException loadToolbar get_property getSessionProperty createPersonProfile opt_in_capturing opt_out_capturing has_opted_in_capturing has_opted_out_capturing clear_opt_in_out_capturing debug getPageViewId".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);
      posthog.init('<%= ENV["POSTHOG_KEY"] %>', {
          api_host: 'https://us.i.posthog.com',
          person_profiles: 'always', // or 'always' to create profiles for anonymous users as well
      })
  </script>
<% end %>
<% if ENV["GOOGLE_ANALYTICS_ID"].present? %>
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV["GOOGLE_ANALYTICS_ID"] %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '<%= ENV["GOOGLE_ANALYTICS_ID"] %>');
  </script>
<% end %>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div>
    <div class="rounded-none! alert <%= msg_type == 'notice' ? 'alert-success' : 'alert-error' %> alert-dismissible fade show" role="alert">
      <%= message.html_safe %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>