config/routes.rb
Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Avo::Engine, at: Avo.configuration.root_path
    Avo::Engine.routes.draw do
      # This route is not protected, secure it with authentication if needed.
      get "dashboard", to: "tools#dashboard", as: :dashboard
      post "login_as/:id", to: "tools#login_as", as: :login_as
    end
  end
  resources :accounts, only: [ :create ] do
    resources :account_users, only: %i[create index destroy], module: :accounts
    member do
      get :switch
    end
  end
  namespace :inbound_webhooks do
    resources :github, controller: :github, only: [ :create ]
    resources :gitlab, controller: :gitlab, only: [ :create ]
  end
  get "/privacy", to: "static#privacy"
  get "/terms", to: "static#terms"

  authenticated :user do
    root to: "projects#index", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end
  get "/integrations/github/repositories", to: "integrations/github/repositories#index"
  resources :add_ons do
    collection do
      get :search
      get :default_values
    end
    member do
      post :restart
    end
    resource :metrics, only: [ :show ], module: :add_ons
    resources :endpoints, only: %i[edit update], module: :add_ons
    resources :processes, only: %i[index show], module: :add_ons
  end

  resources :providers, only: %i[index new create destroy]
  resources :projects do
    member do
      post :restart
    end
    collection do
      get "/:project_id/deployments", to: "projects/deployments#index", as: :root
    end
    resources :project_forks, only: %i[index edit create], module: :projects
    resources :volumes, only: %i[index new create destroy], module: :projects
    resources :processes, only: %i[index show create destroy], module: :projects
    resources :services, only: %i[index new create destroy update], module: :projects do
      resources :jobs, only: %i[create], module: :services
      resources :domains, only: %i[create destroy], module: :services do
        collection do
          post :check_dns
        end
      end
    end
    resources :metrics, only: [ :index ], module: :projects
    resources :project_add_ons, only: %i[create destroy], module: :projects
    resources :environment_variables, only: %i[index create destroy], module: :projects
    resources :deployments, only: %i[index show], module: :projects do
      collection do
        post :deploy
      end
      member do
        post :redeploy
        patch :kill
      end
    end
  end
  resources :clusters do
    member do
      post :transfer_ownership
      get :download_kubeconfig
      get :download_yaml
      get :logs
    end
    resource :metrics, only: [ :show ], module: :clusters
    resource :build_cloud, only: [ :show, :edit, :update, :create, :destroy ], module: :clusters
    member do
      post :test_connection
      post :retry_install
    end
    collection do
      post :check_k3s_ip_address
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      mount Flipper::UI.app(Flipper) => '/flipper', as: :flipper
      mount GoodJob::Engine => "/good_job"
    end
  end

  resources :notifications, only: [ :index ]
  resources :announcements, only: [ :index ]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: "users/sessions" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "async_render" => "async_renderer#async_render"

  get "/calculator", to: "static#calculator"
  # Public marketing homepage
  if Rails.application.config.local_mode
    get "/github_token", to: "local/pages#github_token"
    put "/github_token", to: "local/pages#update_github_token"
    namespace :local do
      resources :onboarding, only: [ :index ]
      resource :portainer, only: [ :show, :update ] do
        collection do
          get :github_oauth
        end
      end
    end
    root to: "projects#index"
  else
    root to: "static#index"
  end
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  owner_id   :bigint
#
# Indexes
#
#  index_accounts_on_owner_id  (owner_id)
#
# Foreign Keys
#
#  fk_rails_...  (owner_id => users.id)
#
class Account < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :account_users, dependent: :destroy
  has_many :users, through: :account_users
  has_one :stack_manager, dependent: :destroy

  has_many :clusters, dependent: :destroy
  has_many :build_clouds, through: :clusters
  has_many :projects, through: :clusters
  has_many :add_ons, through: :clusters
  has_many :services, through: :projects

  def github_username
    return unless github_provider

    JSON.parse(github_provider.auth)["info"]["nickname"]
  end

  def github_access_token
    github_provider&.access_token
  end

  def github_provider
    @_github_account ||= owner.providers.find_by(provider: "github")
  end
end

app/views/accounts/account_users/index.html.erb
<%= content_for :title, "Users" %>
<%= turbo_stream_from [:account_users, current_account] %>

<div>
  <div>
    <h3 class="text-lg font-medium">Team Members</h3>
    <div class="flex text-sm">
      <div class="flex items-center gap-1">
        <iconify-icon icon="lucide:building"></iconify-icon>
        <%= @account.name %>
      </div>
      <div class="flex items-center ml-4 gap-1">
        <iconify-icon icon="lucide:users"></iconify-icon>
        <%= @account.users.count %> Member<%= "s" if @account.users.count != 1 %>
      </div>
    </div>
  </div>

  <div class="mt-5">
    <div aria-label="Card" class="card card-bordered bg-base-100">
      <div class="card-body">
        <div class="text-right px-5 pt-5">
            <!--  Start: User Action -->
             <button class="btn btn-primary btn-sm" onclick="team_member_modal.showModal()">
                <iconify-icon icon="lucide:plus" height="16"></iconify-icon>
                <span class="hidden sm:inline">Add Team Member</span>
              </button>
            <!--  End: User Action -->
            </div>

        <div>
          <%= tag.div id: ("account_users" if @pagy.page == 1) do %>
            <%= render "accounts/account_users/index", account_users: @account_users, cached: true %>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <% if @pagy.pages > 1 %>
    <div class="flex items-center justify-end px-5 pb-5 pt-3">
      <%== custom_pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>

<!-- Start: Click Outside Modal -->
<dialog aria-label="Modal" class="modal" id="team_member_modal">
  <div class="modal-box">
    <form method="dialog">
      <button aria-label="Close modal" class="btn btn-circle btn-ghost btn-sm absolute right-2 top-2">
        <iconify-icon icon="lucide:x" height="16"></iconify-icon>
      </button>
    </form>
    <div class="mb-4 w-full text-xl font-bold">Invite Team Member to <%= @account.name %></div>
    <div>
      <%= form_with(model: User.new, url: account_account_users_path) do |form| %>
        <div class="form-control mt-1 w-full">
          <label class="label">
            <span class="label-text">Email</span>
          </label>
          <%= form.text_field :email, type: :email, class: "input input-bordered w-full focus:outline-offset-0" %>
          <label class="label">
            <span class="label-text-alt">Use the email associated with their Canine account.</span>
          </label>
        </div>
        <div class="form-footer">
          <%= form.button "Invite", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>
<!-- End: Click Outside Modal -->